name: driver_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.30+30

environment:
  sdk: ">=2.19.0 <3.0.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/launcher_icon.png
  remove_alpha_ios: true
  min_sdk_android: 21

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.5
  build_runner: ^2.3.2
  json_annotation: ^4.7.0
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  flutter_riverpod: ^2.1.1
  firebase_messaging: ^14.1.3
  flutter_svg: ^1.1.6
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6
  sign_in_with_apple: ^4.2.0
  http: ^0.13.5
  intl: ^0.17.0
  file_picker: ^5.2.4
  firebase_storage: ^11.0.7
  flutter_switch: ^0.3.2
  device_preview: ^1.1.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.16
  flutter_launcher_icons: ^0.11.0
  location: ^4.2.0
  equatable: ^2.0.5
  geocoding: ^2.0.5
  uuid: ^3.0.7
  cloud_functions: ^4.0.7
  custom_info_window: ^1.0.1
  flutter_styled_toast: ^2.1.3
  geofence_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/map.txt
    - assets/svgs/
    - assets/svgs/icons/
    - assets/png/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
